project:
  type: website
  output-dir: docs

website:
  title: "51 Days in Japan"
  page-navigation: true
  sidebar:
    style: floating
    search: true
    contents: pages

format:
  html:
    theme: journal
    toc: true
